# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 42))
        self.menubar.setObjectName("menubar")
        self.menuExchange = QtWidgets.QMenu(self.menubar)
        self.menuExchange.setObjectName("menuExchange")
        self.menuGold = QtWidgets.QMenu(self.menubar)
        self.menuGold.setObjectName("menuGold")
        self.menuCrypto = QtWidgets.QMenu(self.menubar)
        self.menuCrypto.setObjectName("menuCrypto")
        self.menuExchange_2 = QtWidgets.QMenu(self.menubar)
        self.menuExchange_2.setObjectName("menuExchange_2")
        self.menuNews = QtWidgets.QMenu(self.menubar)
        self.menuNews.setObjectName("menuNews")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuExchange.menuAction())
        self.menubar.addAction(self.menuGold.menuAction())
        self.menubar.addAction(self.menuCrypto.menuAction())
        self.menubar.addAction(self.menuExchange_2.menuAction())
        self.menubar.addAction(self.menuNews.menuAction())

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuExchange.setTitle(_translate("MainWindow", "Currency"))
        self.menuGold.setTitle(_translate("MainWindow", "Gold"))
        self.menuCrypto.setTitle(_translate("MainWindow", "Crypto"))
        self.menuExchange_2.setTitle(_translate("MainWindow", "Exchange"))
        self.menuNews.setTitle(_translate("MainWindow", "News"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
