
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 580)
        MainWindow.setMinimumSize(QtCore.QSize(493, 580))
        MainWindow.setStyleSheet("#centralwidget{\n"
"background-color: rgb(217, 183, 234);\n"
"}\n"
"#frame{\n"
"image: url(:/home/Martin-Berube-Flat-Animal-Turtle.256.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 42))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(12)
        font.setBold(True)
        self.toolBar.setFont(font)
        self.toolBar.setStyleSheet("")
        self.toolBar.setIconSize(QtCore.QSize(96, 64))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionBlue = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blue/Martin-Berube-Flat-Animal-Bird.256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlue.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.actionBlue.setFont(font)
        self.actionBlue.setShortcutVisibleInContextMenu(False)
        self.actionBlue.setObjectName("actionBlue")
        self.actionGreen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/green/Martin-Berube-Flat-Animal-Frog.256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGreen.setIcon(icon1)
        self.actionGreen.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionGreen.setObjectName("actionGreen")
        self.actionPurple = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/purple/Martin-Berube-Flat-Animal-Squid.256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPurple.setIcon(icon2)
        self.actionPurple.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionPurple.setObjectName("actionPurple")
        self.actionRed = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/red/Martin-Berube-Flat-Animal-Crab.256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRed.setIcon(icon3)
        self.actionRed.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionRed.setObjectName("actionRed")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBlue)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPurple)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionBlue.setText(_translate("MainWindow", " Blue"))
        self.actionBlue.setToolTip(_translate("MainWindow", "select animal"))
        self.actionGreen.setText(_translate("MainWindow", "Green"))
        self.actionGreen.setToolTip(_translate("MainWindow", "Select animal"))
        self.actionPurple.setText(_translate("MainWindow", "Purple"))
        self.actionPurple.setToolTip(_translate("MainWindow", "select animal"))
        self.actionRed.setText(_translate("MainWindow", "Red"))
        self.actionRed.setToolTip(_translate("MainWindow", "Select animal"))
import icons_rc
