
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(639, 456)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_adjective = QtWidgets.QGroupBox(Form)
        self.groupBox_adjective.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_adjective.setObjectName("groupBox_adjective")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 150, 99, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 110, 141, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 270, 99, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 310, 99, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_adjective)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 70, 141, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.groupBox_adjective)
        self.groupBox_noun = QtWidgets.QGroupBox(Form)
        self.groupBox_noun.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_noun.setObjectName("groupBox_noun")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 150, 61, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 110, 51, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 270, 99, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 190, 71, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 310, 99, 20))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_noun)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 70, 51, 20))
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout.addWidget(self.groupBox_noun)
        self.groupBox_verb = QtWidgets.QGroupBox(Form)
        self.groupBox_verb.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_verb.setObjectName("groupBox_verb")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_17.setGeometry(QtCore.QRect(10, 150, 99, 20))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_18.setGeometry(QtCore.QRect(10, 110, 141, 20))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_19.setGeometry(QtCore.QRect(10, 230, 141, 20))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_20.setGeometry(QtCore.QRect(10, 270, 121, 20))
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_21.setGeometry(QtCore.QRect(10, 190, 181, 20))
        self.radioButton_21.setObjectName("radioButton_21")
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_22.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_23.setGeometry(QtCore.QRect(10, 310, 121, 31))
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(self.groupBox_verb)
        self.radioButton_24.setGeometry(QtCore.QRect(10, 70, 141, 20))
        self.radioButton_24.setObjectName("radioButton_24")
        self.horizontalLayout.addWidget(self.groupBox_verb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("SENTENCE")
        self.groupBox_adjective.setTitle(_translate("Form", "Adjective"))
        self.radioButton_4.setText(_translate("Form", "Killer"))
        self.radioButton_3.setText(_translate("Form", "Drowned"))
        self.radioButton_6.setText(_translate("Form", "Homophobic"))
        self.radioButton_7.setText(_translate("Form", "Bigot"))
        self.radioButton_5.setText(_translate("Form", "Non-Existent"))
        self.radioButton.setText(_translate("Form", "Introvert"))
        self.radioButton_8.setText(_translate("Form", "Shattered"))
        self.radioButton_2.setText(_translate("Form", "Triangle"))
        self.groupBox_noun.setTitle(_translate("Form", "Noun"))
        self.radioButton_9.setText(_translate("Form", "Hitler"))
        self.radioButton_10.setText(_translate("Form", "Lay"))
        self.radioButton_11.setText(_translate("Form", "Bungalow"))
        self.radioButton_12.setText(_translate("Form", "Skull"))
        self.radioButton_13.setText(_translate("Form", "Foreign"))
        self.radioButton_14.setText(_translate("Form", "Roommate"))
        self.radioButton_15.setText(_translate("Form", "Pineapple"))
        self.radioButton_16.setText(_translate("Form", "Ant"))
        self.groupBox_verb.setTitle(_translate("Form", "Verb"))
        self.radioButton_17.setText(_translate("Form", "fell in love"))
        self.radioButton_18.setText(_translate("Form", "met with aliens"))
        self.radioButton_19.setText(_translate("Form", "took over the world"))
        self.radioButton_20.setText(_translate("Form", "blew up Venus"))
        self.radioButton_21.setText(_translate("Form", "ate last slice of cake"))
        self.radioButton_22.setText(_translate("Form", "dead"))
        self.radioButton_23.setText(_translate("Form", "shared thoughts \n"
"silently"))
        self.radioButton_24.setText(_translate("Form", "solved the secret"))
        self.label.setText(_translate("Form", "Hello!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
